import { Account, AccountStatus, NormalBalance } from '../../models/account.model';

/**
 * Mock account data for local development and testing.
 * Includes edge cases: various statuses, zero-value codes, special characters.
 * @internal
 */
export const MOCK_ACCOUNTS: Account[] = [
    {
        id: 1,
        code: 1000,
        name: 'Cash and Cash Equivalents',
        typeId: 1,
        typeDescription: 'Asset',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-06-15T10:30:00Z',
    },
    {
        id: 2,
        code: 1100,
        name: 'Accounts Receivable',
        typeId: 1,
        typeDescription: 'Asset',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-03-20T14:15:00Z',
    },
    {
        id: 3,
        code: 1200,
        name: 'Investment Securities',
        typeId: 1,
        typeDescription: 'Asset',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-12-01T09:00:00Z',
    },
    {
        id: 4,
        code: 2000,
        name: 'Accounts Payable',
        typeId: 2,
        typeDescription: 'Liability',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-11-30T16:45:00Z',
    },
    {
        id: 5,
        code: 2100,
        name: 'Accrued Expenses',
        typeId: 2,
        typeDescription: 'Liability',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-10-15T11:20:00Z',
    },
    {
        id: 6,
        code: 3000,
        name: 'Share Capital',
        typeId: 3,
        typeDescription: 'Equity',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2023-12-31T23:59:00Z',
    },
    {
        id: 7,
        code: 3100,
        name: 'Retained Earnings',
        typeId: 3,
        typeDescription: 'Equity',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-12-31T23:59:00Z',
    },
    {
        id: 8,
        code: 4000,
        name: 'Investment Income',
        typeId: 4,
        typeDescription: 'Revenue',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-12-15T08:30:00Z',
    },
    {
        id: 9,
        code: 4100,
        name: 'Dividend Income',
        typeId: 4,
        typeDescription: 'Revenue',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Credit,
        normalBalanceDescription: 'Credit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-11-01T12:00:00Z',
    },
    {
        id: 10,
        code: 5000,
        name: 'Management Fees',
        typeId: 5,
        typeDescription: 'Expense',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-12-10T15:45:00Z',
    },
    {
        id: 11,
        code: 5100,
        name: 'Administrative Expenses',
        typeId: 5,
        typeDescription: 'Expense',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-09-30T10:15:00Z',
    },
    {
        id: 12,
        code: 9999,
        name: 'Deprecated Account (Inactive)',
        typeId: 5,
        typeDescription: 'Expense',
        status: AccountStatus.Inactive,
        statusDescription: 'Inactive',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2019-01-01T00:00:00Z',
        updatedAt: '2022-12-31T23:59:00Z',
    },
    {
        id: 13,
        code: 1,
        name: 'Account with Minimal Code Value',
        typeId: 1,
        typeDescription: 'Asset',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 14,
        code: 8888,
        name: 'Account with Special Chars: €$£¥ & <>"',
        typeId: 1,
        typeDescription: 'Asset',
        status: AccountStatus.Active,
        statusDescription: 'Active',
        normalBalance: NormalBalance.Debit,
        normalBalanceDescription: 'Debit',
        createdAt: '2023-06-15T12:00:00Z',
        updatedAt: '2024-06-15T12:00:00Z',
    },
];
