import { Fund, ValuationFrequency } from '../../models/fund.model';

/**
 * Mock fund data for local development and testing.
 * Includes realistic edge cases: various currencies, dates, and frequencies.
 * @internal
 */
export const MOCK_FUNDS: Fund[] = [
    {
        id: 1,
        code: 'FUND001',
        name: 'Global Equity Growth Fund',
        baseCurrency: 'USD',
        inceptionDate: '2020-01-15',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2020-01-15T10:00:00Z',
        updatedAt: '2024-12-01T14:30:00Z',
    },
    {
        id: 2,
        code: 'FUND002',
        name: 'Fixed Income Bond Portfolio',
        baseCurrency: 'EUR',
        inceptionDate: '2019-06-01',
        valuationFrequency: ValuationFrequency.Weekly,
        valuationFrequencyDescription: 'Weekly',
        createdAt: '2019-06-01T09:00:00Z',
        updatedAt: '2024-11-15T11:20:00Z',
    },
    {
        id: 3,
        code: 'FUND003',
        name: 'Emerging Markets Opportunities',
        baseCurrency: 'USD',
        inceptionDate: '2021-03-10',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2021-03-10T08:30:00Z',
    },
    {
        id: 4,
        code: 'FUND004',
        name: 'Sustainable Energy & Technology',
        baseCurrency: 'GBP',
        inceptionDate: '2022-09-01',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2022-09-01T10:00:00Z',
        updatedAt: '2024-10-20T16:45:00Z',
    },
    {
        id: 5,
        code: 'FUND005',
        name: 'Asia-Pacific Growth',
        baseCurrency: 'JPY',
        inceptionDate: '2018-11-20',
        valuationFrequency: ValuationFrequency.Weekly,
        valuationFrequencyDescription: 'Weekly',
        createdAt: '2018-11-20T07:00:00Z',
        updatedAt: '2024-09-30T13:00:00Z',
    },
    {
        id: 6,
        code: 'FUND-SPECIAL',
        name: 'Fund with Special Characters: Â£$€¥ & "Quotes"',
        baseCurrency: 'CHF',
        inceptionDate: '2023-01-01',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2023-01-01T00:00:00Z',
    },
    {
        id: 7,
        code: 'FUND007',
        name: 'Very Long Fund Name That Tests UI Constraints And Demonstrates How The System Handles Extended Text Fields Beyond Normal Expectations',
        baseCurrency: 'USD',
        inceptionDate: '2024-01-01',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2024-01-01T12:00:00Z',
    },
    {
        id: 8,
        code: 'LUX-REIT',
        name: 'Luxembourg Real Estate Investment Trust',
        baseCurrency: 'EUR',
        inceptionDate: '2017-05-15',
        valuationFrequency: ValuationFrequency.Weekly,
        valuationFrequencyDescription: 'Weekly',
        createdAt: '2017-05-15T14:00:00Z',
        updatedAt: '2024-08-10T09:30:00Z',
    },
    {
        id: 9,
        code: 'BALANCED-MIX',
        name: 'Balanced Multi-Asset Portfolio',
        baseCurrency: 'CAD',
        inceptionDate: '2020-07-01',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2020-07-01T10:30:00Z',
    },
    {
        id: 10,
        code: 'CRYPTO-FUTURE',
        name: 'Digital Assets & Blockchain Innovation',
        baseCurrency: 'USD',
        inceptionDate: '2023-06-15',
        valuationFrequency: ValuationFrequency.Daily,
        valuationFrequencyDescription: 'Daily',
        createdAt: '2023-06-15T15:00:00Z',
        updatedAt: '2024-12-15T10:00:00Z',
    },
];
