import { Security, SecurityStatus, SecurityType } from '../../models/security.model';

/**
 * Mock security data for local development and testing.
 * Includes edge cases: nulls, special characters, various types and statuses.
 * @internal
 */
export const MOCK_SECURITIES: Security[] = [
    {
        id: 1,
        name: 'Apple Inc.',
        ticker: 'AAPL',
        isin: 'US0378331005',
        type: SecurityType.Equity,
        typeDescription: 'Equity',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2020-01-15T10:00:00Z',
        updatedAt: '2024-12-01T14:30:00Z',
        deactivatedAt: null,
    },
    {
        id: 2,
        name: 'Microsoft Corporation',
        ticker: 'MSFT',
        isin: 'US5949181045',
        type: SecurityType.Equity,
        typeDescription: 'Equity',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2020-01-15T10:05:00Z',
        updatedAt: '2024-11-28T09:15:00Z',
        deactivatedAt: null,
    },
    {
        id: 3,
        name: 'US Treasury Bond 10Y',
        ticker: 'UST10Y',
        isin: 'US912828Z282',
        type: SecurityType.Bond,
        typeDescription: 'Bond',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2020-02-01T08:00:00Z',
        updatedAt: '2024-10-15T16:20:00Z',
        deactivatedAt: null,
    },
    {
        id: 4,
        name: 'Vanguard S&P 500 ETF',
        ticker: 'VOO',
        isin: 'US9229083632',
        type: SecurityType.ETF,
        typeDescription: 'ETF',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2020-03-10T11:30:00Z',
        updatedAt: '2024-12-10T10:45:00Z',
        deactivatedAt: null,
    },
    {
        id: 5,
        name: 'Bitcoin Futures Contract',
        ticker: 'BTCF',
        isin: null,
        type: SecurityType.Future,
        typeDescription: 'Future',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2021-06-15T14:00:00Z',
        updatedAt: '2024-12-15T12:00:00Z',
        deactivatedAt: null,
    },
    {
        id: 6,
        name: 'EUR/USD Foreign Exchange',
        ticker: 'EURUSD',
        isin: null,
        type: SecurityType.FX,
        typeDescription: 'FX',
        currency: 'EUR',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2020-01-01T00:00:00Z',
        updatedAt: '2024-12-20T08:30:00Z',
        deactivatedAt: null,
    },
    {
        id: 7,
        name: 'Gold Commodity',
        ticker: 'XAU',
        isin: null,
        type: SecurityType.Commodity,
        typeDescription: 'Commodity',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2019-11-20T13:00:00Z',
        updatedAt: '2024-11-30T15:45:00Z',
        deactivatedAt: null,
    },
    {
        id: 8,
        name: 'Deprecated Stock (Inactive)',
        ticker: 'OLDSTK',
        isin: 'US1234567890',
        type: SecurityType.Equity,
        typeDescription: 'Equity',
        currency: 'USD',
        status: SecurityStatus.Inactive,
        statusDescription: 'Inactive',
        createdAt: '2018-01-01T00:00:00Z',
        updatedAt: '2022-12-31T23:59:00Z',
        deactivatedAt: '2022-12-31T23:59:00Z',
    },
    {
        id: 9,
        name: 'Security with Special Characters: Ä Ö Ü & "Quotes"',
        ticker: 'SPEC-CHAR',
        isin: 'DE0001234567',
        type: SecurityType.Equity,
        typeDescription: 'Equity',
        currency: 'EUR',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2023-01-15T10:00:00Z',
        updatedAt: '2024-08-20T11:30:00Z',
        deactivatedAt: null,
    },
    {
        id: 10,
        name: 'Very Long Security Name That Tests The User Interface Constraints And Demonstrates How The System Handles Extended Text',
        ticker: 'LONGNAME',
        isin: 'GB0123456789',
        type: SecurityType.Equity,
        typeDescription: 'Equity',
        currency: 'GBP',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-06-15T09:00:00Z',
        deactivatedAt: null,
    },
    {
        id: 11,
        name: 'S&P 500 Index',
        ticker: 'SPX',
        isin: null,
        type: SecurityType.Index,
        typeDescription: 'Index',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2019-01-01T00:00:00Z',
        updatedAt: '2024-12-18T16:00:00Z',
        deactivatedAt: null,
    },
    {
        id: 12,
        name: 'AAPL Call Option',
        ticker: 'AAPL-C-200',
        isin: null,
        type: SecurityType.OptionOnEquity,
        typeDescription: 'OptionOnEquity',
        currency: 'USD',
        status: SecurityStatus.Active,
        statusDescription: 'Active',
        createdAt: '2023-09-01T10:00:00Z',
        updatedAt: '2024-09-15T14:30:00Z',
        deactivatedAt: null,
    },
];
