import {Transaction, TransactionStatus, TransactionSubType} from '../../models/transaction.model';

/**
 * Mock transaction data for local development and testing.
 * Includes various transaction types, statuses, and edge cases.
 * @internal
 */
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 1,
    fundId: 1,
    fundCode: 'FND001',
    fundName: 'Alpha Growth Fund',
    securityId: 1,
    securityTicker: 'AAPL',
    securityName: 'Apple Inc.',
    transactionSubTypeId: 1,
    transactionSubTypeDescription: 'Buy',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-15',
    settleDate: '2024-01-17',
    quantity: 100,
    price: 185.50,
    amount: 18550.00,
    currency: 'USD',
    statusId: 2,
    statusDescription: 'Confirmed',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T14:30:00Z',
  },
  {
    id: 2,
    fundId: 1,
    fundCode: 'FND001',
    fundName: 'Alpha Growth Fund',
    securityId: 2,
    securityTicker: 'MSFT',
    securityName: 'Microsoft Corporation',
    transactionSubTypeId: 1,
    transactionSubTypeDescription: 'Buy',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-16',
    settleDate: '2024-01-18',
    quantity: 50,
    price: 390.25,
    amount: 19512.50,
    currency: 'USD',
    statusId: 3,
    statusDescription: 'Settled',
    createdAt: '2024-01-16T09:15:00Z',
    updatedAt: '2024-01-18T16:00:00Z',
  },
  {
    id: 3,
    fundId: 2,
    fundCode: 'FND002',
    fundName: 'Beta Income Fund',
    securityId: 3,
    securityTicker: 'GOOGL',
    securityName: 'Alphabet Inc.',
    transactionSubTypeId: 2,
    transactionSubTypeDescription: 'Sell',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-17',
    settleDate: '2024-01-19',
    quantity: -25,
    price: 142.80,
    amount: -3570.00,
    currency: 'USD',
    statusId: 1,
    statusDescription: 'Pending',
    createdAt: '2024-01-17T11:30:00Z',
    updatedAt: null,
  },
  {
    id: 4,
    fundId: 1,
    fundCode: 'FND001',
    fundName: 'Alpha Growth Fund',
    securityId: null,
    securityTicker: null,
    securityName: null,
    transactionSubTypeId: 3,
    transactionSubTypeDescription: 'Deposit',
    transactionTypeId: 3,
    transactionTypeDescription: 'Cash',
    tradeDate: '2024-01-10',
    settleDate: '2024-01-10',
    quantity: 1,
    price: 100000.00,
    amount: 100000.00,
    currency: 'USD',
    statusId: 3,
    statusDescription: 'Settled',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 5,
    fundId: 2,
    fundCode: 'FND002',
    fundName: 'Beta Income Fund',
    securityId: 4,
    securityTicker: 'AMZN',
    securityName: 'Amazon.com Inc.',
    transactionSubTypeId: 1,
    transactionSubTypeDescription: 'Buy',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-18',
    settleDate: '2024-01-22',
    quantity: 75,
    price: 155.30,
    amount: 11647.50,
    currency: 'USD',
    statusId: 2,
    statusDescription: 'Confirmed',
    createdAt: '2024-01-18T13:45:00Z',
    updatedAt: '2024-01-18T15:00:00Z',
  },
  {
    id: 6,
    fundId: 1,
    fundCode: 'FND001',
    fundName: 'Alpha Growth Fund',
    securityId: 5,
    securityTicker: 'NVDA',
    securityName: 'NVIDIA Corporation',
    transactionSubTypeId: 1,
    transactionSubTypeDescription: 'Buy',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-19',
    settleDate: '2024-01-23',
    quantity: 30,
    price: 545.75,
    amount: 16372.50,
    currency: 'USD',
    statusId: 1,
    statusDescription: 'Pending',
    createdAt: '2024-01-19T10:20:00Z',
    updatedAt: null,
  },
  {
    id: 7,
    fundId: 3,
    fundCode: 'FND003',
    fundName: 'Global Balanced Fund',
    securityId: 6,
    securityTicker: 'TSM',
    securityName: 'Taiwan Semiconductor',
    transactionSubTypeId: 1,
    transactionSubTypeDescription: 'Buy',
    transactionTypeId: 1,
    transactionTypeDescription: 'Equity',
    tradeDate: '2024-01-20',
    settleDate: '2024-01-24',
    quantity: 200,
    price: 108.50,
    amount: 21700.00,
    currency: 'USD',
    statusId: 2,
    statusDescription: 'Confirmed',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-20T11:30:00Z',
  },
  {
    id: 8,
    fundId: 2,
    fundCode: 'FND002',
    fundName: 'Beta Income Fund',
    securityId: null,
    securityTicker: null,
    securityName: null,
    transactionSubTypeId: 4,
    transactionSubTypeDescription: 'Withdrawal',
    transactionTypeId: 3,
    transactionTypeDescription: 'Cash',
    tradeDate: '2024-01-21',
    settleDate: '2024-01-21',
    quantity: 1,
    price: -25000.00,
    amount: -25000.00,
    currency: 'USD',
    statusId: 3,
    statusDescription: 'Settled',
    createdAt: '2024-01-21T14:00:00Z',
    updatedAt: '2024-01-21T14:00:00Z',
  },
];

/**
 * Mock transaction statuses for local development.
 * @internal
 */
export const MOCK_TRANSACTION_STATUSES: TransactionStatus[] = [
  {
    id: 1,
    shortDescription: 'Pending',
    longDescription: 'Transaction is pending approval or processing',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 2,
    shortDescription: 'Confirmed',
    longDescription: 'Transaction has been confirmed and is awaiting settlement',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 3,
    shortDescription: 'Settled',
    longDescription: 'Transaction has been fully settled',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 4,
    shortDescription: 'Cancelled',
    longDescription: 'Transaction has been cancelled',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 5,
    shortDescription: 'Failed',
    longDescription: 'Transaction failed to process',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
];

/**
 * Mock transaction sub-types for local development.
 * @internal
 */
export const MOCK_TRANSACTION_SUBTYPES: TransactionSubType[] = [
  {
    id: 1,
    typeId: 1,
    typeDescription: 'Equity',
    shortDescription: 'Buy',
    longDescription: 'Purchase equity securities',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 2,
    typeId: 1,
    typeDescription: 'Equity',
    shortDescription: 'Sell',
    longDescription: 'Sell equity securities',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 3,
    typeId: 3,
    typeDescription: 'Cash',
    shortDescription: 'Deposit',
    longDescription: 'Cash deposit into fund',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 4,
    typeId: 3,
    typeDescription: 'Cash',
    shortDescription: 'Withdrawal',
    longDescription: 'Cash withdrawal from fund',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 5,
    typeId: 2,
    typeDescription: 'Fixed Income',
    shortDescription: 'Buy',
    longDescription: 'Purchase fixed income securities',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 6,
    typeId: 2,
    typeDescription: 'Fixed Income',
    shortDescription: 'Sell',
    longDescription: 'Sell fixed income securities',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 7,
    typeId: 3,
    typeDescription: 'Cash',
    shortDescription: 'Dividend',
    longDescription: 'Dividend income received',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
  {
    id: 8,
    typeId: 3,
    typeDescription: 'Cash',
    shortDescription: 'Interest',
    longDescription: 'Interest income received',
    createdAt: '2020-01-01T00:00:00Z',
    updatedAt: null,
  },
];
